apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-redis-vahe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-redis-vahe
  template:
    metadata:
      labels:
        app: node-redis-vahe
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: node-redis-vahe
          image: cloud.canister.io:5000/arhturescriou/node-redis
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: REDIS_URL
              value: "redis://redis-vahe-service:6379"
