apiVersion: v1
kind: Service
metadata:
  name: redis-node-vahe-service
spec:
  selector:
    app: node-redis-vahe
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: redis-vahe-service
spec:
  selector:
    app: redis-vahe
  ports:
    - port: 6379
      targetPort: 6379
  type: LoadBalancer